[paritytech.polkadot]
organization = "paritytech"
repository = "polkadot"
query-release = true # Currently, we only track releases from polkadot.

[paritytech.substrate]
organization = "paritytech"
repository = "substrate"
query-release = false

[paritytech.cumulus]
organization = "paritytech"
repository = "cumulus"
query-release = false

[paritytech.frontier]
organization = "paritytech"
repository = "frontier"
query-release = false

[PureStake.nimbus]
organization = "PureStake"
repository = "nimbus"
query-release = false

[open-web3-stack.orml]
organization = "open-web3-stack"
repository = "open-runtime-module-library"
query-release = false

# template
# [organization.repository]
# organization = "organization-name"
# repository = "repository-name"
# query-release = false

[schedule]
frequence = 7200 # Query issues and PRs every 2(3600 * 2) hours

[discord]
bot-token = "123456789"
issue-channel = "" # where to send new issues
merged-pr-channel = "" # where to send merge PRs
new-pr-channel = "" # where to send new created PRs
latest-release-channel = "" # where to send latest release
